// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
package __TOP_LEVEL_PACKAGE__.__SEGMENT_PACKAGE__;

import com.google.gwt.event.shared.EventBus;
import com.google.inject.Inject;
import __SHARED_TOP_LEVEL_PACKAGE__.managed.request.ApplicationRequestFactory;
import __TOP_LEVEL_PACKAGE__.application.DesktopShell;

public class AccountHelper {

	@Inject
	public AccountHelper(DesktopShell shell, ApplicationRequestFactory requestFactory, EventBus eventBus) {
		__ACCOUNT_HOOKUP__
	}
}