package org.springframework.roo.addon.requestfactory.android.types;

public enum Permission {
    ACCESS_CHECKIN_PROPERTIES ("android.permission.ACCESS_CHECKIN_PROPERTIES"),
    ACCESS_COARSE_LOCATION ("android.permission.ACCESS_COARSE_LOCATION"),
    ACCESS_FINE_LOCATION ("android.permission.ACCESS_FINE_LOCATION"),
    ACCESS_LOCATION_EXTRA_COMMANDS ("android.permission.ACCESS_LOCATION_EXTRA_COMMANDS"),
    ACCESS_MOCK_LOCATION ("android.permission.ACCESS_MOCK_LOCATION"),
    ACCESS_NETWORK_STATE ("android.permission.ACCESS_NETWORK_STATE"),
    ACCESS_SURFACE_FLINGER ("android.permission.ACCESS_SURFACE_FLINGER"),
    ACCESS_WIFI_STATE ("android.permission.ACCESS_WIFI_STATE"),
    BATTERY_STATS ("android.permission.BATTERY_STATS"),
    BIND_APPWIDGET ("android.permission.BIND_APPWIDGET"),
    BIND_INPUT_METHOD ("android.permission.BIND_INPUT_METHOD"),
    BLUETOOTH ("android.permission.BLUETOOTH"),
    BLUETOOTH_ADMIN ("android.permission.BLUETOOTH_ADMIN"),
    BRICK ("android.permission.BRICK"),
    BROADCAST_PACKAGE_REMOVED ("android.permission.BROADCAST_PACKAGE_REMOVED"),
    BROADCAST_SMS ("android.permission.BROADCAST_SMS"),
    BROADCAST_STICKY ("android.permission.BROADCAST_STICKY"),
    BROADCAST_WAP_PUSH ("android.permission.BROADCAST_WAP_PUSH"),
    CALL_PHONE ("android.permission.CALL_PHONE"),
    CALL_PRIVILEGED ("android.permission.CALL_PRIVILEGED"),
    CAMERA ("android.permission.CAMERA"),
    CHANGE_COMPONENT_ENABLED_STATE ("android.permission.CHANGE_COMPONENT_ENABLED_STATE"),
    CHANGE_CONFIGURATION ("android.permission.CHANGE_CONFIGURATION"),
    CHANGE_NETWORK_STATE ("android.permission.CHANGE_NETWORK_STATE"),
    CHANGE_WIFI_MULTICAST_STATE ("android.permission.CHANGE_WIFI_MULTICAST_STATE"),
    CHANGE_WIFI_STATE ("android.permission.CHANGE_WIFI_STATE"),
    CLEAR_APP_CACHE ("android.permission.CLEAR_APP_CACHE"),
    CLEAR_APP_USER_DATA ("android.permission.CLEAR_APP_USER_DATA"),
    CONTROL_LOCATION_UPDATES ("android.permission.CONTROL_LOCATION_UPDATES"),
    DELETE_CACHE_FILES ("android.permission.DELETE_CACHE_FILES"),
    DELETE_PACKAGES ("android.permission.DELETE_PACKAGES"),
    DEVICE_POWER ("android.permission.DEVICE_POWER"),
    DIAGNOSTIC ("android.permission.DIAGNOSTIC"),
    DISABLE_KEYGUARD ("android.permission.DISABLE_KEYGUARD"),
    DUMP ("android.permission.DUMP"),
    EXPAND_STATUS_BAR ("android.permission.EXPAND_STATUS_BAR"),
    FACTORY_TEST ("android.permission.FACTORY_TEST"),
    FLASHLIGHT ("android.permission.FLASHLIGHT"),
    FORCE_BACK ("android.permission.FORCE_BACK"),
    GET_ACCOUNTS ("android.permission.GET_ACCOUNTS"),
    GET_PACKAGE_SIZE ("android.permission.GET_PACKAGE_SIZE"),
    GET_TASKS ("android.permission.GET_TASKS"),
    GLOBAL_SEARCH ("android.permission.GLOBAL_SEARCH"),
    HARDWARE_TEST ("android.permission.HARDWARE_TEST"),
    INJECT_EVENTS ("android.permission.INJECT_EVENTS"),
    INSTALL_LOCATION_PROVIDER ("android.permission.INSTALL_LOCATION_PROVIDER"),
    INSTALL_PACKAGES ("android.permission.INSTALL_PACKAGES"),
    INTERNAL_SYSTEM_WINDOW ("android.permission.INTERNAL_SYSTEM_WINDOW"),
    INTERNET ("android.permission.INTERNET"),
    MANAGE_APP_TOKENS ("android.permission.MANAGE_APP_TOKENS"),
    MASTER_CLEAR ("android.permission.MASTER_CLEAR"),
    MODIFY_AUDIO_SETTINGS ("android.permission.MODIFY_AUDIO_SETTINGS"),
    MODIFY_PHONE_STATE ("android.permission.MODIFY_PHONE_STATE"),
    MOUNT_FORMAT_FILESYSTEMS ("android.permission.MOUNT_FORMAT_FILESYSTEMS"),
    MOUNT_UNMOUNT_FILESYSTEMS ("android.permission.MOUNT_UNMOUNT_FILESYSTEMS"),
    PERSISTENT_ACTIVITY ("android.permission.PERSISTENT_ACTIVITY"),
    PROCESS_OUTGOING_CALLS ("android.permission.PROCESS_OUTGOING_CALLS"),
    READ_CALENDAR ("android.permission.READ_CALENDAR"),
    READ_CONTACTS ("android.permission.READ_CONTACTS"),
    READ_FRAME_BUFFER ("android.permission.READ_FRAME_BUFFER"),
    READ_HISTORY_BOOKMARKS ("com.android.browser.permission.READ_HISTORY_BOOKMARKS"),
    READ_INPUT_STATE ("android.permission.READ_INPUT_STATE"),
    READ_LOGS ("android.permission.READ_LOGS"),
    READ_OWNER_DATA ("android.permission.READ_OWNER_DATA"),
    READ_PHONE_STATE ("android.permission.READ_STATE_PHONE"),
    READ_SMS ("android.permission.READ_SMS"),
    READ_SYNC_SETTINGS ("android.permission.READ_SYNC_SETTINGS"),
    READ_SYNC_STATS ("android.permission.READ_SYNC_STATS"),
    REBOOT ("android.permission.REBOOT"),
    RECEIVE_BOOT_COMPLETED ("android.permission.RECEIVE_BOOT_COMPLETED"),
    RECEIVE_MMS ("android.permission.RECEIVE_MMS"),
    RECEIVE_SMS ("android.permission.RECEIVE_SMS"),
    RECEIVE_WAP_PUSH ("android.permission.RECEIVE_WAP_PUSH"),
    RECORD_AUDIO ("android.permission.RECORD_AUDIO"),
    REORDER_TASKS ("android.permission.REORDER_TASKS"),
    RESTART_PACKAGES ("android.permission.RESTART_PACKAGES"),
    SEND_SMS ("android.permission.SEND_SMS"),
    SET_ACTIVITY_WATCHER ("android.permission.SET_ACTIVITY_WATCHER"),
    SET_ALWAYS_FINISH ("android.permission.SET_ALWAYS_FINISH"),
    SET_ANIMATION_SCALE ("android.permission.SET_ANIMATION_SCALE"),
    SET_DEBUG_APP ("android.permission.SET_DEBUG_APP"),
    SET_ORIENTATION ("android.permission.SET_ORIENTATION"),
    SET_PREFERRED_APPLICATIONS ("android.permission.SET_PREFERRED_APPLICATIONS"),
    SET_PROCESS_LIMIT ("android.permission.SET_PROCESS_LIMIT"),
    SET_TIME_ZONE ("android.permission.SET_TIME_ZONE"),
    SET_WALLPAPER ("android.permission.SET_WALLPAPER"),
    SET_WALLPAPER_HINTS ("android.permission.SET_WALLPAPER_HINTS"),
    SIGNAL_PERSISTENT_PROCESSES ("android.permission.SIGNAL_PERSISTENT_PROCESSES"),
    STATUS_BAR ("android.permission.STATUS_BAR"),
    SUBSCRIBED_FEEDS_READ ("android.permission.SUBSCRIBED_FEEDS_READ"),
    SUBSCRIBED_FEEDS_WRITE ("android.permission.SUBSCRIBED_FEEDS_WRITE"),
    SYSTEM_ALERT_WINDOW ("android.permission.SYSTEM_ALERT_WINDOW"),
    UPDATE_DEVICE_STATS ("android.permission.UPDATE_DEVICE_STATS"),
    VIBRATE ("android.permission.VIBRATE"),
    WAKE_LOCK ("android.permission.WAKE_LOCK"),
    WRITE_APN_SETTINGS ("android.permission.WRITE_APN_SETTINGS"),
    WRITE_CALENDAR ("android.permission.WRITE_CALENDAR"),
    WRITE_CONTACTS ("android.permission.WRITE_CONTACTS"),
    WRITE_EXTERNAL_STORAGE ("android.permission.WRITE_EXTERNAL_STORAGE"),
    WRITE_GSERVICES ("android.permission.WRITE_GSERVICES"),
    WRITE_HISTORY_BOOKMARKS ("com.android.browser.permission.WRITE_HISTORY_BOOKMARKS"),
    WRITE_OWNER_DATA ("android.permission.WRITE_OWNER_DATA"),
    WRITE_SECURE_SETTINGS ("android.permission.WRITE_SECURE_SETTINGS"),
    WRITE_SETTINGS ("android.permission.WRITE_SETTINGS"),
    WRITE_SMS ("android.permission.WRITE_SMS"),
    WRITE_SYNC_SETTINGS ("android.permission.WRITE_SYNC_SETTINGS");

    private final String className;

    private Permission(final String className) {
        this.className = className;
    }

    public String permissionName() {
        return className;
    }
}
